### ISSUE TITLE
Crimea is marked incorrectly.

### ISSUE THREAD

**Issue by patsore** [SebLague/Geographical-Adventures#107]
Hi,
I couldn't help but notice that the map you used had incorrectly demarcated Crimea as being part of russia, not Ukraine, as is recognized by most countries.
It would be greatly appreciated if you could change that.
(a few images of that)
![image](https://user-images.githubusercontent.com/80210497/197195055-cbf20642-8fa8-4831-b42d-2c3669037704.png)
 
![image](https://user-images.githubusercontent.com/80210497/197194829-431ff3f8-10f9-4d71-9fa5-b71e1792f49c.png)

**Comment by SebLague** [comment]
Hello, this has already been fixed in the second video :)
