### ISSUE TITLE
Wind particles?

### ISSUE THREAD

**Issue by Sheaffy** [SebLague/Geographical-Adventures#14]
Hi, Would it be possible to see the code that does the wind particles as I believe it is missing?
Im guessing it was a decision to not include it in the final commit, however seeing how that works would be really beneficial!

Thanks for the awesome work.

**Comment by SebLague** [comment]
Hi -- sorry for the late response. The side-experiments like the wind particles are currently only available as a bonus to patrons of the channel. They'll be made public to everyone in a few weeks though, at which point you'll be able to access them (if by any chance you're still interested) over [here](https://www.patreon.com/posts/source-code-for-65893075).
