### ISSUE TITLE
[bug] sun and moon stopped revolving

### ISSUE THREAD

**Issue by arrowgent** [SebLague/Geographical-Adventures#17]
at some point after about 30 minutes in one of my sessions the sun and moon stopped revolving around

i noticed this and flew to the two poles in a circle for a minute or two watching as neither celestial body moved

no idea what caused this error

**Comment by SebLague** [comment]
Interesting, I'll have to investigate that... Thanks!

**Comment by SebLague** [comment]
I haven't seen this happening in the new version so closing for now.
