### ISSUE TITLE
[Suggestion] Add a compass

### ISSUE THREAD

**Issue by WolverinDEV** [SebLague/Geographical-Adventures#2]
Hey,
it's an awesome project and I really love the amount of detail you put into visualizing the world.
Just flying around, I noticed that I easily loose track of where I am (Maybe I just suck at geography^^).

My suggestion would be to add something like a compass in one of the corners.

Greetings

**Comment by SebLague** [comment]
Hey, thanks I'm happy you like it! I've actually already added a compass and map in my development version -- it will be added here once I've finished working on the next video.
