### ISSUE TITLE
Details on the tweaks for flat earth

### ISSUE THREAD

**Issue by noahlavelle** [SebLague/Geographical-Adventures#22]
Hey, 
I was wondering what sort of changes you made to the mesh generation system to allow for flat earths (I believe you briefly mentioned it in the second video but didn't go into much detail).
Any help as to the rough locations of code that could be changed would be appreciated

**Comment by SebLague** [comment]
Hello, please see the 'worldIsSpherical' setting in the player class https://github.com/SebLague/Geographical-Adventures/blob/main/Assets/Scripts/Game/Player/Player.cs
