### ISSUE TITLE
Earth rotation 

### ISSUE THREAD

**Issue by RIZ3Nsoul** [SebLague/Geographical-Adventures#23]
Earth rotation is not working. Textures stay at the same position in the world space

**Comment by wischi-chr** [comment]
It's called "world space" for a reason 😄  jokes aside, does that even matter to the player?

**Comment by SebLague** [comment]
You can modify the terrain shader to use object space tex coords if you need this, but in the game I keep the earth stationary and rotate sun/moon etc. instead.
