### ISSUE TITLE
[Suggestion] Relaxing background music

### ISSUE THREAD

**Issue by WolverinDEV** [SebLague/Geographical-Adventures#3]
Hey,
it's me again with just another idea I had.

What about some chill background music?
This makes the experience flying around, just exploring the word or doing deliveries much more exciting imo.
My personal preference would be some kind of relaxing, calm music (like within your yt videos)

Greetings

**Comment by SebLague** [comment]
Will definitely be adding some music soon, thanks for the feedback :)
