### ISSUE TITLE
[Bug] There is no city in Guatemala called 'Guatemala'

### ISSUE THREAD

**Issue by EvilsSouls** [SebLague/Geographical-Adventures#34]
There is no city in Guatemala called 'Guatemala'. Could be because the author of the 7k Cities didn't put any city down for Guatemala.

![image](https://user-images.githubusercontent.com/86242809/166303998-7524396a-81a8-4b10-8d7f-122670f70e4e.png)

**Comment by TomCaserta** [comment]
The capitol city of Guatemala is Guatemala; https://en.wikipedia.org/wiki/Guatemala_City 

Unless you are stating something else?

**Comment by EvilsSouls** [comment]
> The capital city of Guatemala is Guatemala; https://en.wikipedia.org/wiki/Guatemala_City
> 
> Unless you are stating something else?

I'm pretty sure the Capital is Guatemala City, not Guatemala...

**Comment by TomCaserta** [comment]
It is known as both (just asked someone next to me who is from Guatemala) Guatemala and Guatemala City (for clarifying you are talking about the city specifically).

Google also shows the following:

<img width="320" alt="Screenshot 2022-05-02 at 23 27 17" src="https://user-images.githubusercontent.com/592309/166330485-3114df36-b309-45ea-925d-1de4a323972e.png">

vs Panama City:

<img width="281" alt="Screenshot 2022-05-02 at 23 28 23" src="https://user-images.githubusercontent.com/592309/166330622-c99faf98-e8ea-458d-a620-9fd9211268bb.png">


I think like most thing depends on context and location of the speaker that being said 'Guatemala' should be okay here.

**Comment by EvilsSouls** [comment]
Oh... I didn't realize that.
