### ISSUE TITLE
[Suggestion] VR mode

### ISSUE THREAD

**Issue by SleepyBoi2852** [SebLague/Geographical-Adventures#4]
Ok so hear me out, I think it'd be sick if there was a VR mode so here is the entire idea:

Controls Ideas:
1. Fly the plane and drop packages with the controllers (preferably turning with the Right Joystick, and dropping packages with "A" or Trigger (or you could add a setting for people who are left handed or right handed))
2. Fly the plane with an in-game joystick that you can grab, and you can use the A or Trigger button to drop a package.

Perspective Ideas:
1. Third Person (above the plane)
2. First Person (In the plane)

Other Ideas:
1. Settings so you're able to change between several different types of controllers, including hands

Platform Ideas:
1. SteamVR (Using SteamVR Plugin)
2. Android (Oculus Quest)

If you do decide add this, Maybe use the SteamVR Plugin, or export it to Android/Oculus Quest (or both I guess idk).

**Comment by SebLague** [comment]
Thanks for the ideas. Gamepad support has now been added (still experimental though). Will keep VR in mind for the future.
