### ISSUE TITLE
Linux build script

### ISSUE THREAD

**Issue by l0b0** [SebLague/Geographical-Adventures#40]
I'm hoping to be able to [build this using Nix](https://discourse.nixos.org/t/how-to-build-unity-project/18960), but I know next to nothing about Unity. Would you be willing to share the script you use for building for Linux (or some instructions I could use to translate into a script if you build it using a GUI)?

**Comment by ajh123** [comment]
Unity allows you to compile to Linux if you got the Linux build system installed

**Comment by l0b0** [comment]
@ajh123 What do you mean? It sounds like a tautology.

**Comment by SebLague** [comment]
You need to open the project in the Unity editor and build it from the GUI there.
