### ISSUE TITLE
Please release (or early release) on Steam for easy updates

### ISSUE THREAD

**Issue by adam248** [SebLague/Geographical-Adventures#41]
As the title says

**Comment by Joshix-1** [comment]
Just use the itch app https://itch.io/app
It allows for easy updates.

**Comment by AdyStudios** [comment]
Steam costs quite a bit of money, and making an own launcher is like 10 minutes, so yes the best option currently is itch.io, no need for steam

**Comment by SebLague** [comment]
Might consider steam in the future, but for now it's a bit too much of a hassle for me, sorry.
