### ISSUE TITLE
Réunion is named France in the Map

### ISSUE THREAD

**Issue by Inst1nct007** [SebLague/Geographical-Adventures#58]
The Original picture from google earth

![Google Earth — Mozilla Firefox 5_5_2022 2_51_09 PM](https://user-images.githubusercontent.com/94550979/166895939-9ee22260-0e87-4ad8-8145-485f8670d7f1.png)

The In Game Map

![Geographical Adventures 5_5_2022 2_50_57 PM](https://user-images.githubusercontent.com/94550979/166896076-4f8950ac-a000-4cd0-a20a-201def5cff91.png)

This game is a masterpiece. I have always been interested in geography, now I can finally learn it without getting bored! Thanks for that!

**Comment by juleslagarde** [comment]
Réunion is part of france.

**Comment by Inst1nct007** [comment]
> Réunion is part of france.
