### ISSUE TITLE
Feature Request: Add translations

### ISSUE THREAD

**Issue by MillersMan** [SebLague/Geographical-Adventures#68]
I love this game as I like geography and would love to let my children play it. Unfortunately their knowledge of English isn't good enough to play it in its current form.

If there was a language-support I would love to take the time to add German translations.

**Comment by SebLague** [comment]
Hi, thanks for the suggestion. I'd definitely like to support different languages. Would translations of country names be sufficient (for now) for them to be able to play, or is the user interface being in English the bigger hurdle?

**Comment by tposejank** [comment]
The user interface and the country names would be what's best to change. If there was language support I would love to add Spanish (México and Spain)

**Comment by Agentew04** [comment]
If translation to Portuguese(pt-br) is needed, I'm happy to help translate it too

**Comment by fsioni** [comment]
Same for french :)

**Comment by MillersMan** [comment]
Country names would be a good start and sufficient for me. But would love to see the user interface translated, too.

**Comment by StuSerious** [comment]
I'd be happy to translate country names and UI to Italian!

**Comment by SebLague** [comment]
I appreciate all the interest! Working on this right now.

**Comment by MrBrain295** [comment]
You could use something like crowdin.

**Comment by SebLague** [comment]
Hi everyone, I've added some info about early community translations over here: #70
