### ISSUE TITLE
[Bug] Pressing space rapidly drops multiple packages.

### ISSUE THREAD

**Issue by dmadisetti** [SebLague/Geographical-Adventures#8]
Pressing space rapidly drops multiple packages.
This also prevents the red city hint from disappearing.

![image](https://user-images.githubusercontent.com/2689338/156456830-1f61438e-94b4-4359-970d-b9ca63c8836f.png)

I just want to say super cool game. I love this 🎉 it's a beautiful game and have already sent an hour or two just messing around. Do you have a space for suggestions?

**Comment by SebLague** [comment]
Thanks I’ll look into it! For suggestions, you’re welcome to just open a new issue.

**Comment by SebLague** [comment]
This should be fixed with the latest version.
