### ISSUE TITLE
RTL support in translations

### ISSUE THREAD

**Issue by zeevro** [SebLague/Geographical-Adventures#91]
I made a Hebrew translation ([here](https://github.com/zeevro/Geographical-Adventures)), but all the text is reversed. I've never done anything in Unity, though, so I have no idea how to fix that. Being a software developer, I guess I could google around and find a fix, but I was wondering if you have a quicker solution for me :)

**Comment by SebLague** [comment]
Hi, thanks for working on a translation! I've added rtl support in the latest commit (you should just need to check the rtl checkbox on the _Hebrew.asset). Please let me know if it's not working correctly.
